name: harpy
description: A Twitter app built with Flutter.

publish_to: 'none'

# android/version.properties is used to manage the versions
version: 0.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  android_path_provider: ^0.3.0
  any_link_preview: ^3.0.0
  built_collection: ^5.1.1
  collection: ^1.15.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.4
  dart_twitter_api: ^0.5.8
  # dart_twitter_api:
  #   path: ../twitter_api
  device_info_plus: ^8.0.0
  download_manager:
    git: https://github.com/robertodoering/download_manager
  dynamic_color: ^1.4.0
  encrypt: ^5.0.1
  file_picker: ^5.0.0
  flare_flutter :
    git:
      url: https://github.com/mdpe-ir/Flare-Flutter
      path: flare_flutter
      ref: stable
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_displaymode: ^0.6.0
  flutter_feather_icons: ^2.0.0+1
  flutter_ffmpeg: ^0.4.0
  flutter_image: ^4.1.0
  flutter_keyboard_visibility: ^5.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.1.0
  go_router:
    git:
      url: https://github.com/robertodoering/packages
      path: packages/go_router
      ref: c0432b8b05bd678b971e1b6bde783c82d9eee98c
  google_fonts: ^4.0.4
  http: ^0.13.3
  humanizer: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.5.0
  location: ^4.4.0
  logging: ^1.0.1
  material_color_utilities: ^0.8.0
  mime_type: ^1.0.0
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^3.0.2
  path_provider: ^2.0.3
  permission_handler: ^10.0.0
  photo_view:
    # photo_view fork with better gesture recognition
    git: https://github.com/bluefireteam/photo_view
  rby:
    git: https://github.com/robertodoering/rby.dart
    # path: ../rby.dart
  riverpod_annotation: ^1.0.6
  scroll_to_index: ^3.0.0
  sentry_flutter: ^7.6.2
  share_plus: ^6.3.0
  shared_preferences: ^2.0.7
  shimmer: ^3.0.0
  sliver_tools: ^0.2.6
  smooth_page_indicator: ^1.0.0+2
  super_sliver_list:
    git:
      url: https://github.com/superlistapp/super_sliver_list
      ref: 196abe17bae1803435d3112fd11c58ef4c2d577e
  timeago: ^3.0.2
  tuple: ^2.0.0
  twitter_api_v2:
    # TODO: use pub when version 4.5.1+ is published
    git: https://github.com/robertodoering/twitter-api-v2

  twitter_webview_auth: ^0.1.1
  url_launcher: ^6.0.10
  uuid: ^3.0.5
  video_player: ^2.1.15
  visibility_detector: ^0.4.0+2
  wakelock: ^0.6.0
  waterfall_flow: ^3.0.1
  webview_flutter: ^3.0.0

dev_dependencies:
  alchemist: ^0.6.0
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  golden_toolkit:
    # golden_toolkit fork to allow for asynchronous device wrappers
    git:
      url: https://github.com/robertodoering/flutter_glove_box
      path: packages/golden_toolkit/
  json_serializable: ^6.0.1
  mocktail: ^0.3.0
  riverpod_generator: ^1.0.6

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/changelogs/free/
    - assets/changelogs/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: NotoSans
      # used as a fallback font
      # covers a lot of scripts and obscure unicode characters
      # https://fonts.google.com/specimen/Noto+Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
